#+TITLE:   Shiwali Mohan
#+AUTHOR:    Shiwali Mohan
#+EMAIL:     shiwali.mohan@gmail.com
#+DESCRIPTION: Shiwali's personal website
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc author:nil
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+BIBLIOGRAPHY: my_library dsgplain option:--both option:-nokeys option:-linebreak option:-nofooter
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Esteban|Gentium+Book+Basic' rel='stylesheet' type='text/css'>
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
#+STYLE: <LINK href="css/stylesheet.css" rel="stylesheet" type="text/css">
#+STYLE: <script src="javascripts/jquery.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.hashchange.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.easytabs.js" type="text/javascript"></script>  
#+STYLE: <script type="text/javascript"> $(document).ready(function(){ $('#tab-container').easytabs();});</script>
# End:



#+BEGIN_HTML
<div id="tab-container">
<ul>
    <li><a href="#outline-container-1">» about «</a></li>
    <li><a href="#outline-container-2">» research  «</a></li>
    <li><a href="#bibliography">» publications  «</a></li>
    <li><a href="#outline-container-3">» academia «</a></li>
  </ul>
#+END_HTML

* About

I am a doctoral candidate in [[http://www.cse.umich.edu/][Computer Science and Engineering]] at [[http://www.umich.edu/][The
University of Michigan]] Ann Arbor. I have been working with Professor [[http://ai.eecs.umich.edu/people/laird/][John Laird]]
on the [[http://sitemaker.umich.edu/soar/home][Soar Cognitive Architecture]] in the [[http://www.eecs.umich.edu/ai/][Michigan AI Lab]] since 2009.

I am interested in situated language for intelligent agents and the
relationship of language processing (comprehension, acquisiton,
generation and interaction) with other cognitive capabilities such as
perception, procedural and declarative knowledge, and learning. 

My past work has focussed on cognitive agents that can learn to
navigate new, complex environments. We have looked at agents that
start with minimal background knowledge about an environment and build
relevant, relational structures using reinforcement learning in the
[[http://2009.rl-competition.org/mario.php][Infinite Mario]] RL domain.

I am from India, where I recieved an undergraduate degree in
[[http://en.wikipedia.org/wiki/Instrumentation][Instrumentation and Control Engineering]] from [[http://www.du.ac.in/index.php?id%3D4][University of
Delhi]]. After four years of struggling with control equations and
diffrential calculus, I ended up loving programming and other geeky,
Computer Science-y things. I worked with [[http://in.careers.yahoo.com/][Yahoo! India]] as a software
engineer on their Strategic Data Solutions team for  time, before
deciding to denounce the real world, and the money that comes with it
and became a graduate student.

-----
I am available at shiwali.at.umich.dot.edu and
shiwali.dot.mohan.at.gmail.dot.com. My curriculum vitae dated 17-05-2012 is [[file:resume/resume.pdf][here]]. 

* Research
*** Grounded Natural Language
I am involved with the grounded language acquisition project
at Michigan. Apart from the Soar group at University of Michigan, the
team also includes [[http://april.eecs.umich.edu/][APRIL at Michigan]] and [[http://www.soartech.com/][SoarTech]].

I am currently studying comprehension of sentences by exploiting
non-linguistic context such as perceptual information, procedural
knowledge and semantic information.

I have designed and implemented an interaction model for agents
instantiated in Soar cognitive architecture that allows limited
mixed-initiative interaction with an instructor. The
agents can then derive generally applicable procedural knowledge from
a history of interactions (available in episodic/semantic memory of
the agent) using situated explanation. 

Related Software: [[https://github.com/mtinkerhess/sbolt][SBOLT]], [[https://github.com/shiwalimohan/bolt-agents][Soar Agents]], [[http://code.google.com/p/soar/][Soar]]
-------
*** Reinforcement Learning
In the past, I was investigating the capabilities of Soar-RL in
complex environments. I designed, implemented and analyzed
reinforcement learning agents for Infinite Mario. I also implemented modular
reinforcement learning for Soar cognitive architecture that allows the
agent to learn multiple MDPs at the same time.

Related Software:
[[https://github.com/shiwalimohan/MarioSoar][MarioSoar]]
* Academia
*** Teaching
I served as a graduate student instructor for EECS 492 - Introduction
to Artificial Intelligence in Winter 2012 at University of Michigan.\\
Course material: [[https://github.com/shiwalimohan/eecs492UM/zipball/master][zip archive]] | [[https://github.com/shiwalimohan/eecs492UM][github]]
-------
*** Advising
I am a founding member of the [[http://www.edulix.com/forum/forumdisplay.php?fid%3D105][EduMentoring]] initiative - a bunch of
graduate students who volunteer as undergraduate research mentors to
students in India.\\
\\
Fall 2011, Winter 2012: Advised [[mandarjoshi.90@gmail.com][Mandar Joshi]], [[khobragade.rakesh@gmail.com][Rakesh Khobragade]],
[[sonusaurabhsarda@gmail.com][Saurabh Sarda]] on designing Reinforcement Learning agents for Infinite
Mario. The work was submitted as final year thesis project to the CS
department, [[http://www.vnit.ac.in/][VNIT]], Pune, India.

-------
*** Service
Co-chair, Special Interest Group on Faculty ([[https://wiki.eecs.umich.edu/sigfaculty/index.php/Main_Page][SIG-Faculty]]) at
University of Michigan. 2012.\\
Vice-President, Computer Science and Engineering Graduate student
organization ([[http://cseg.eecs.umich.edu/][CSEG]]) at University of Michigan. 2011. \\
Creative Lead, Indian Students Association ([[umisa.org][ISA]]) at University of Michigan. 2011\\
DCO Representative, Computer Science and Engineering Graduate student
organization ([[http://cseg.eecs.umich.edu/][CSEG]]) at Univesity of Michigan. 2010.
Social Chair, Indian Students Association ([[umisa.org][ISA]]) at University of
Michigan. 2010\\
-------
*** Talks
[[https://web.eecs.umich.edu/~soar/workshop/files/27_mohan1_modular.pdf][Modular Reinforcement Learning In Soar]], 
31st Soar Workshop, June 2011, Ann Arbor Michigan \\
[[https://web.eecs.umich.edu/~soar/workshop/files/35_mohan2_architecture.pdf][Towards an Architecture for Learning with Instruction]], 
31st Soar Workshop, June 2011, Ann Arbor Michigan \\
[[http://ai.eecs.umich.edu/soar/sitemaker/workshop/30/mohan1.pdf][Reinforcement Learning in Infinite Mario]], 
30th Soar Workshop, June 2010, Ann Arbor Michigan \\
[[http://ai.eecs.umich.edu/soar/sitemaker/workshop/30/mohan2.pdf][Learning Background Knowledge thorugh Instruction]], 
30th Soar Workshop, June 2010, Ann Arbor Michigan \\
[[http://sitemaker.umich.edu/soar/files/mohan.pdf][Learning to Play Mario]], 
29th Soar Workshop, June 2009, Ann Arbor, Michigan \\
-------
*** Miscellaneous Projects
[[file:content/mohan_EECS545.pdf][On Generating Grounded Language in Cognitive Architecture]], 
EECS 590, Natural Language Processing, April 2011, University of Michigan\\
[[file:content/prelim-paper.pdf][Relational Reinforcement Learning in Infinite Mario]], 
Preliminary Examination, September 2010, University of Michigan \\
[[file:content/MohanPillaiSleight.pdf][Classification of Executed and Imagined Motor Movement EEG Signals]],
EECS 545, Machine Learning, December 2009, University of Michigan\\
[[file:content/hadoop.pdf][Towards a Resource Aware Scheduler in Hadoop]],
EECS 589, Advanced Computer Networks, December 2009, University of
Michigan
