#+TITLE:   Shiwali Mohan
#+AUTHOR:    Shiwali Mohan
#+EMAIL:     shiwali.mohan@gmail.com
#+DESCRIPTION: Shiwali's personal website
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc author:nil
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+BIBLIOGRAPHY: my_library dsgplain option:--both option:-nokeys option:-linebreak option:-nofooter
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Esteban|Gentium+Book+Basic' rel='stylesheet' type='text/css'>
#+STYLE: <LINK href="css/stylesheet.css" rel="stylesheet" type="text/css">
#+STYLE: <script src="javascripts/jquery.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.hashchange.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.easytabs.js" type="text/javascript"></script>  
#+STYLE: <script type="text/javascript"> $(document).ready(function(){ $('#tab-container').easytabs();});</script>
# End:

#+BEGIN_HTML
<div id="tab-container">
  <ul>
    <li><a href="#outline-container-1">About</a></li>
    <li><a href="#bibliography">Publications</a></li>
  </ul>
#+END_HTML

* About
I am a doctoral candidate in [[http://www.cse.umich.edu/][Computer Science and Engineering]] at [[http://www.umich.edu/][The
University of Michigan]] Ann Arbor. I have been working with Professor [[http://ai.eecs.umich.edu/people/laird/][John Laird]]
on the [[http://sitemaker.umich.edu/soar/home][Soar Cognitive Architecture]] in the [[http://www.eecs.umich.edu/ai/][Michigan AI Lab]] since 2009.

I am interested in situated language for intelligent agents and the
relationship of language processing (comprehension, acquisiton,
generation and interaction) with other cognitive capabilities such as
perception, procedural and declarative knowledge, and learning. 

My past work has focussed on cognitive agents that can learn to
navigate new, complex environments. We have looked at agents that
start with minimal background knowledge about an environment and build
relevant, relational structures using reinforcement learning in the
[[http://2009.rl-competition.org/mario.php][Infinite Mario]] RL domain.

I am from India, where I recieved an undergraduate degree in
[[http://en.wikipedia.org/wiki/Instrumentation][Instrumentation and Control Engineering]] from [[http://www.du.ac.in/index.php?id%3D4][University of
Delhi]]. After four years of struggling with control equations and
diffrential calculus, I ended up loving programming and other geeky,
Computer Science-y things. I worked with [[http://in.careers.yahoo.com/][Yahoo! India]] as a software
engineer on their Strategic Data Solutions team for  time, before
deciding to denounce the real world, and the money that comes with it
and became a graduate student.

-------
I am available at shiwali.at.umich.dot.edu,
shiwali.dot.mohan.at.gmail.dot.com. My curriculum vitae dated <04-04-2012 Wed> is [[file:resume/resume.pdf][here]]. 

