#+TITLE:   Shiwali Mohan
#+AUTHOR:    Shiwali Mohan
#+EMAIL:     shiwali.mohan@gmail.com
#+DESCRIPTION: Shiwali's personal website
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc author:nil
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Esteban|Gentium+Book+Basic' rel='stylesheet' type='text/css'>
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
#+STYLE: <LINK href="css/stylesheet.css" rel="stylesheet" type="text/css">
#+STYLE: <script src="javascripts/jquery.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.hashchange.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.easytabs.js" type="text/javascript"></script>  
#+STYLE: <script type="text/javascript"> $(document).ready(function(){ $('#tab-container').easytabs();});</script>
#+STYLE:   <script src ="javascripts/BibTex-0.1.2.js" type="text/javascript"></script>
#+STYLE:    <script type="text/javascript" src="javascripts/displayBibTex.js"></script>
#+STYLE: <script type="text/javascript">function displayBoth(){displayBibTex('text-4','bib_publi');} window.onload=displayBoth;</script>

#+BEGIN_HTML        


<div id="tab-container">
<ul>
    <li><a href="#outline-container-1">» about «</a></li>
    <li><a href="#outline-container-2">» research  «</a></li>
    <li><a href="#outline-container-4">» publications  «</a></li>
    <li><a href="#outline-container-3">» academia «</a></li>
  </ul>
#+END_HTML


* About

I am a doctoral candidate in [[http://www.cse.umich.edu/][Computer Science and Engineering]] at [[http://www.umich.edu/][The
University of Michigan]], Ann Arbor. I have been working with Professor [[http://ai.eecs.umich.edu/people/laird/][John Laird]]
on the [[http://sitemaker.umich.edu/soar/home][Soar Cognitive Architecture]] in the [[http://www.eecs.umich.edu/ai/][Michigan AI Lab]] since 2009.

I am interested in situated language for intelligent agents and the
relationship of language processing (comprehension, acquisition,
generation and interaction) with other cognitive capabilities such as
perception, procedural and declarative knowledge, and learning. 

My past work has focused on cognitive agents that can learn to
navigate new, complex environments. We have looked at agents that
start with minimal background knowledge about an environment and build
relevant, relational structures using reinforcement learning in the
[[http://2009.rl-competition.org/mario.php][Infinite Mario]] RL domain.

I am from India, where I received an undergraduate degree in
[[http://en.wikipedia.org/wiki/Instrumentation][Instrumentation and Control Engineering]] from [[http://www.du.ac.in/index.php?id%3D4][University of
Delhi]]. After four years of struggling with control equations and
differential calculus, I ended up loving programming and other geeky,
Computer Science-y things. I worked with [[http://in.careers.yahoo.com/][Yahoo! India]] as a software
engineer on their Strategic Data Solutions team for some time, before
deciding to denounce the real world, and the money that comes with it
and became a graduate student.

-----
I am available at shiwali.at.umich.dot.edu and
shiwali.dot.mohan.at.gmail.dot.com. My curriculum vitae dated
26-10-2012 is [[file:resume/resume.pdf][here]]. My google citation page is [[http://scholar.google.com/citations?hl%3Den&user%3DEYWzxPIAAAAJ][here]].

* Research

*** Grounded Natural Language
I am involved with the grounded language acquisition project
at Michigan. Apart from the Soar group at University of Michigan, the
team also includes [[http://april.eecs.umich.edu/][APRIL at Michigan]] and [[http://www.soartech.com/][SoarTech]].

I am currently studying comprehension of sentences by exploiting
non-linguistic context such as perceptual information, procedural
knowledge and semantic information.

I have designed and implemented an interaction model for agents
instantiated in Soar cognitive architecture that allows limited
mixed-initiative interaction with an instructor. The
agents can then derive generally applicable procedural knowledge from
a history of interactions (available in episodic/semantic memory of
the agent) using situated explanation. 

Related Software: [[https://github.com/mtinkerhess/sbolt][SBOLT]], [[https://github.com/shiwalimohan/bolt-agents][Soar Agents]], [[http://code.google.com/p/soar/][Soar]]

#+begin_html
<iframe width="390" height="220" src="http://www.youtube.com/embed/9M-rpdXFbgs" frameborder="0" allowfullscreen></iframe>

<iframe width="390" height="220" src="http://www.youtube.com/embed/_ktny-h0KX4" frameborder="0" allowfullscreen></iframe>
#+end_html
*** Reinforcement Learning
In the past, I was investigating the capabilities of Soar-RL in
complex environments. I designed, implemented and analyzed
reinforcement learning agents for Infinite Mario. I also implemented modular
reinforcement learning for Soar cognitive architecture that allows the
agent to learn multiple MDPs at the same time.

Related Software:
[[https://github.com/shiwalimohan/MarioSoar][MarioSoar]]

* Academia
*** Thesis
My thesis work investigates acquistion of novel task knowledge through natural-language like human-robot interaction. \\
Writing: [[file:content/thesis-proposal.pdf][thesis proposal]] \\
Talks: [[file:content/thesis-proposal-talk.pdf][thesis proposal]]
-------
*** Teaching
I served as a graduate student instructor for EECS 492 - Introduction
to Artificial Intelligence in Winter 2012 at University of Michigan.\\
Course material: [[https://github.com/shiwalimohan/eecs492UM/zipball/master][zip archive]] | [[https://github.com/shiwalimohan/eecs492UM][github]]
-------
*** Advising
I am a founding member of the [[http://www.edulix.com/forum/forumdisplay.php?fid%3D105][EduMentoring]] initiative - a bunch of
graduate students who volunteer as undergraduate research mentors to
students in India.\\
\\
Fall 2012, Winter 2013: Advising [[mittal.anant@gmail.com][Anant Mittal]], [[anmol.gupta91@gmail.com][Anmol Gupta]] on
designing Soar AI agents for Google AI Challenge - Planet Wars. The
work is to be submitted as a minor project to the CS department,
[[http://www.bvcoend.ac.in//][BVCOE]], New Delhi, India.\\
\\
Fall 2011, Winter 2012: Advised [[mandarjoshi.90@gmail.com][Mandar Joshi]], [[khobragade.rakesh@gmail.com][Rakesh Khobragade]],
[[sonusaurabhsarda@gmail.com][Saurabh Sarda]] on designing Reinforcement Learning agents for Infinite
Mario. The work was submitted as final year thesis project to the CS
department, [[http://www.vnit.ac.in/][VNIT]], Nagpur, India.

-------
*** Service
Co-chair, Special Interest Group on Faculty ([[https://wiki.eecs.umich.edu/sigfaculty/index.php/Main_Page][SIG-Faculty]]) at
University of Michigan. 2012.\\
Vice-President, Computer Science and Engineering Graduate student
organization ([[http://cseg.eecs.umich.edu/][CSEG]]) at University of Michigan. 2011. \\
Creative Lead, Indian Students Association ([[umisa.org][ISA]]) at University of Michigan. 2011\\
DCO Representative, Computer Science and Engineering Graduate student
organization ([[http://cseg.eecs.umich.edu/][CSEG]]) at University of Michigan. 2010.
Social Chair, Indian Students Association ([[umisa.org][ISA]]) at University of
Michigan. 2010\\
-------
*** Talks
[[http://shiwali.me/content/interaction.pdf][Mixed-Initiative Interaction for Learning with Instruction]],
32nd Soar Workshop, June 2012, Ann Arbor, Michigan\\
[[http://shiwali.me/content/comprehension.pdf][Situated Comprehension of Action Commands]],
32nd Soar Workshop, June 2012, Ann Arbor, Michigan\\
[[http://shiwali.me/content/verb-learning.pdf][Learning New Verbs with Retrospective Projection]],
32nd Soar Workshop, June 2012, Ann Arbor, Michigan\\
[[http://ai.eecs.umich.edu/soar/sitemaker/workshop/31/files/27_mohan1_modular.pdf][Modular Reinforcement Learning In Soar]], 
31st Soar Workshop, June 2011, Ann Arbor, Michigan \\
[[http://ai.eecs.umich.edu/soar/sitemaker/workshop/31/files/35_mohan2_architecture.pdf][Towards an Architecture for Learning with Instruction]], 
31st Soar Workshop, June 2011, Ann Arbor Michigan \\
[[http://ai.eecs.umich.edu/soar/sitemaker/workshop/30/mohan1.pdf][Reinforcement Learning in Infinite Mario]], 
30th Soar Workshop, June 2010, Ann Arbor, Michigan \\
[[http://ai.eecs.umich.edu/soar/sitemaker/workshop/30/mohan2.pdf][Learning Background Knowledge through Instruction]], 
30th Soar Workshop, June 2010, Ann Arbor, Michigan \\
[[http://sitemaker.umich.edu/soar/files/mohan.pdf][Learning to Play Mario]], 
29th Soar Workshop, June 2009, Ann Arbor, Michigan \\
-------
*** Miscellaneous Projects
[[file:content/mohan_EECS545.pdf][On Generating Grounded Language in Cognitive Architecture]], 
EECS 590, Natural Language Processing, April 2011, University of Michigan\\
[[file:content/prelim-paper.pdf][Relational Reinforcement Learning in Infinite Mario]], 
Preliminary Examination, September 2010, University of Michigan \\
[[file:content/MohanPillaiSleight.pdf][Classification of Executed and Imagined Motor Movement EEG Signals]],
EECS 545, Machine Learning, December 2009, University of Michigan\\
[[file:content/hadoop.pdf][Towards a Resource Aware Scheduler in Hadoop]],
EECS 589, Advanced Computer Networks, December 2009, University of
Michigan
* Publications
#+begin_html
<div class ="bib" id = "bib_publi">
@inproceedings{Mohan2012f,
author = {Shiwali Mohan and James Kirk and John Laird},
title = {A Computational Model of Situated Task Learning with
Interactive Instruction},
booktitle = {(to appear) In Proceedings of the 17th International Conference on Cognitive Modeling},
year = {2013},
pdf = {./content/mohan_ICCM_2013.pdf},
type_publi = {conference},
internal-link = {<a href="http://www.shiwali.me/content/mohan_ICCM_2013.pdf">internal link</a>},
}

@inproceedings{Mohan2012f,
author = {Shiwali Mohan and Aaron Mininger and James Kirk and John Laird},
title = {Acquiring Grounded Representations of Words with Situated Interactive Instruction},
booktitle = {Advances in Cognitive Systems, 2},
year = {2012},
pdf = {./content/mohan_ACS_2012.pdf},
type_publi = {journal},
url = {http://www.cogsys.org/pdf/paper-3-2-136.pdf},
talk = {./content/acs-talk.pdf},
internal-link = {<a href="http://www.shiwali.me/content/mohan_ACS_2012.pdf">internal link</a>},
}

@inproceedings{Joshi2012a,
author = {Mandar Joshi and Rakesh Khobragade and Saurabh Sarda and Umesh Deshpande and Shiwali Mohan},
title = {Object-Oriented Representation and Hierarchical Reinforcement Learning in Infinite Mario},
booktitle = {In Proceedings of the 24th IEEE International Conference on Tools with Artificial Intelligence (ICTAI)},
year = {2012},
pdf = {./content/joshi_ICTAI_2012.pdf},
url = {http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6495169},
type_publi = {workshop},
internal-link = {<a href="http://www.shiwali.me/content/joshi_ICTAI_2012.pdf">internal link</a>},
}

@inproceedings{Mohan2012e,
author = {Shiwali Mohan* and Aaron Mininger* and James Kirk* and John Laird},
title = {Learning Grounded Language through Situated Interactive Instruction},
booktitle = {In Papers from Robots Learning Interactively from Human Teachers (AAAI Fall Symposium Series)},
pdf = {./content/mohan_AAAIFS_2012.pdf},
url = {http://aaai.org/ocs/index.php/FSS/FSS12/paper/view/5662},
year = {2012},
type_publi = {symposium},
url = {http://www.aaai.org/ocs/index.php/FSS/FSS12/paper/view/5662},
talk = {./content/aaaifs-talk.pdf},
internal-link = {<a href="http://www.shiwali.me/content/mohan_AAAIFS_2012.pdf">internal link</a>},
}

@inproceedings{Joshi2012,
author = {Mandar Joshi and Rakesh Khobragade and Saurabh Sarda and Umesh Deshpande and Shiwali Mohan},
title = {Hierarchical Action Selection for Reinforcement Learning in Infinite Mario},
booktitle = {In Proceedings of the 6th Starting Artificial Intelligence Research Symposium (co-located with ECAI)},
year = {2012},
pdf = {./content/joshi_STAIRS_2012.pdf},
url = {http://plata.ar.media.kyoto-u.ac.jp/mori/research/Proceedings/ECAI2012/content/stairs/stairs201215.pdf},
type_publi = {workshop},
url =
{http://books.google.com/books?hl=en&lr=&id=WOc8WSwcCjoC&oi=fnd&pg=PA162&dq=info:Zp20TtDieTIJ:scholar.google.com&ots=u-dG_96A95&sig=X1HmRu-UJj4UZ-8Y2n3YU-SO_eI},
internal-link = {<a href="http://www.shiwali.me/content/joshi_STAIRS_2012.pdf">internal link</a>},
}

@inproceedings{Mohan2012d,
author = {John Laird and Keegan Kinkade and Shiwali Mohan and Joseph Xu},
title = {Cognitive Robotics Using the Soar Cognitive Architecture},
booktitle = {In Proceedings of the 8th International Cognitive Robotics Workshop},
year = {2012},
pdf = {./content/laird_AAAICogRob_2012.pdf},
url =
{http://aaai.org/ocs/index.php/WS/AAAIW12/paper/view/5221},
type_publi = {workshop},
internal-link = {<a href="http://www.shiwali.me/content/laird_AAAICogRob_2012.pdf">internal link</a>},
}

@inproceedings{Mohan2012c,
author = {Shiwali Mohan and John Laird},
title = {Situated Comprehension of Imperative Sentences in Embodied, Cognitive Agents},
booktitle = {Grounding Language for Physical Systems, AAAI
Technical Report WS-12-07},
year = {2012},
pdf = {./content/mohan_AAAIGPS_2012.pdf},
url = {http://aaai.org/ocs/index.php/WS/AAAIW12/paper/view/5245},
type_publi = {workshop},
internal-link = {<a href="http://www.shiwali.me/content/mohan_AAAIGPS_2012.pdf">internal link</a>},
}

@inproceedings{Mohan2012b,
author = {Shiwali Mohan and John Laird},
title = {Exploring Mixed-Initiative Interaction for Learning with Situated Instruction in Cognitive Agents},
booktitle = {Proceedings of the 26th AAAI Conference on Artificial Intelligence},
year = {2012},
pdf = {./content/mohan_AAAISA_2012.pdf},
url = {http://www.aaai.org/ocs/index.php/AAAI/AAAI12/paper/view/4834},
type_publi = {conference},
note = {\textit{(Extended Abstract)}},        
internal-link = {<a href="http://www.shiwali.me/content/mohan_AAAISA_2012.pdf">internal link</a>},
}

@inproceedings{Mohan2012a,
author = {Shiwali Mohan and John Laird},
title = {Learning Actions and Action Verbs from Human-Agent Interaction},
booktitle = {17th AAAI/SIGART Doctoral Consortium},
year = {2012},
keywords = {cognition; Soar; learning with instruction; human agent collaboration, lanugage acquisiton, situated learning},
pdf = {./content/mohan_AAAIDC_2012.pdf},
type_publi = {conference},
url = {http://www.aaai.org/ocs/index.php/AAAI/AAAI12/paper/viewFile/4856/5288},
note = {\textit{(Extended Abstract)}},    
talk = {./content/dc-r.pdf},
internal-link = {<a href="http://www.shiwali.me/content/mohan_AAAIDC_2012.pdf">internal link</a>},
}

@inproceedings{Mohan2011a,
author = {Shiwali Mohan and John Laird},
title = {Towards Situated, Interactive, Instructable Agents in a Cognitive Architecture},
booktitle = {Papers from the 2011 AAAI Fall Symposium Series},
year = {2011},
keywords = {cognition; Soar; learning with instruction; human agent collaboration; rule-based systems},
abstract = {This paper discusses the challenge of designing instructable agents that can learn through interaction with a human expert. Learning through instruction is a powerful paradigm for acquiring knowledge because it limits the complexity of the learning task in a variety of ways. To support learning through instruction, the agent must be able to effectively communicate its lack of knowledge to the human, comprehend instructions, and apply them to the ongoing task. Weidentify some problems of concern when designing instructable agents. We propose an agent design that addresses some of these problems. We instantiate this design in the Soar cognitive architecture and analyze its capabilities on a learning task.},
url = {http://www.aaai.org/ocs/index.php/FSS/FSS11/paper/view/4165},
pdf = {./content/mohan_fss_2011.pdf},
type_publi = {conference},
internal-link = {<a href="http://www.shiwali.me/content/mohan_fss_2011.pdf">internal link</a>},
}

@inproceedings{Mohan2011b,
author = {Shiwali Mohan and John Laird},
title = {An Object-Oriented Approach to Reinforcement Learning in an Action Game},
booktitle = {Proceedings of the Artificial Intelligence for Interactive Digital Entertainment Conference},
keywords = {decision making; reinforcement learning; action games},
abstract = {In this work, we look at the challenge of learning in an action game,Infinite Mario. Learning to play an action game can be divided into two distinct but related problems, learning an object-related behavior and selecting a primitive action. We propose a framework that allows for the use of reinforcement learning for both of these problems. We present promising results in some instances of the game and identify some problems that might affect learning.},
url = {http://www.aaai.org/ocs/index.php/AIIDE/AIIDE11/paper/view/4069},
series = {AIIDE},
year = {2011},
pdf = {./content/mohan_aiide_2011.pdf},
type_publi = {conference},
internal-link = {<a href="http://www.shiwali.me/content/mohan_aiide_2011.pdf">internal link</a>},
}

@inproceedings{Mohan2010,
author = {Shiwali Mohan and John Laird},
title = {Relational Reinforcement Learning in Infinite Mario},
booktitle = {Proceedings of the 24th AAAI Conference on Artificial Intelligence},
abstract = {Relational representations in reinforcement learning allow for the use of structural information like the presence of objects and relationships between them in the description of value functions. Through this paper, we show that such representations allow for the inclusion of background knowledge that qualitatively describes a state and can be used to design agents that demonstrate learning behavior in domains with large state and actions spaces such as computer games.`},
series = {AAAI},
year = {2010},
url = {http://www.aaai.org/ocs/index.php/AAAI/AAAI10/paper/view/1657},
pdf = {./content/mohan.pdf},
note = {\textit{(Extended Abstract)}},
type_publi = {conference},
internal-link = {<a href="http://www.shiwali.me/content/mohan.pdf">internal link</a>},
}


@inproceedings{Mohan2008,
author = {Niladri Chatterjee and Shiwali Mohan},
title = {Discovering Word Senses from Text using Random Indexing},
booktitle = {Proceedings of the 9th International Conference on Computational linguistics and Intelligent Text Processing},
abstract = {Random Indexing is a novel technique for dimensionality reduction while creating Word Space model from a given text. This paper explores the possible application of Random Indexing in discovering word senses from the text. The words appearing in the text are plotted onto a multi-dimensional Word Space using Random Indexing. The geometric distance between words is used as an indicative of their semantic similarity. Soft Clustering by Committee algorithm (CBC) has been used to constellate similar words. The present work shows that the Word Space model can be used effectively to determine the similarity index required for clustering. The approach does not require parsers, lexicons or any other resources which are traditionally used in sense disambiguation of words. The proposed approach has been applied to TASA corpus and encouraging results have been obtained.},
series = {CICLing},
year = {2008},
note = {\textbf{Best Paper Award}},
url = {http://www.springerlink.com/content/xp70kw14w0054541/},
pdf = {./content/mohan_cicling_2008.pdf},
type_publi = {conference},
internal-link = {<a href="http://www.shiwali.me/content/mohan_cicling_2008.pdf">internal link</a>},
} 

@inproceedings{Mohan2007,
author = {Niladri Chatterjee and Shiwali Mohan},
title = {Extraction-Based Single-Document Summarization Using Random Indexing},
booktitle ={Proceeding of the 19th IEEE International Conference on Tools with Artificial Intelligence},
abstract = {This paper presents a summarization technique for text documents exploiting the semantic similarity between sentences to remove the redundancy from the text. Semantic similarity scores are computed by mapping the sentences on a semantic space using Random Indexing. Random Indexing, in comparison with other semantic space algorithms, presents a computationally efficient way of implicit dimensionality reduction. It involves inexpensive vector computations such as addition. It thus provides an efficient way to compute similarities between words, sentences and documents. Random Indexing has been used to compute the semantic similarity scores of sentences and graph-based ranking algorithms have been employed to produce an extract of the given text.},
series = {ICTAI},
year = {2007},
url ={http://www.computer.org/portal/web/csdl/doi/10.1109/ICTAI.2007.28},
pdf ={./content/mohan_ictai.pdf},
type_publi = {conference},
internal-link = {<a href="http://www.shiwali.me/content/mohan_ictai.pdf">internal link</a>},
}


@techreport{Mohan2009,
author = {Shiwali Mohan and John E. Laird},
title = {Learning to Play Mario},
NUMBER =        {CCA-TR-2009-03},
booktitle = {Technical Report CCA-TR-2009-03 Center for
Cognitive Architecture, University of Michigan, Ann Arbor, Michigan},
INSTITUTION =   {Center for Cognitive Architecture, University of Michigan},
ADDRESS =       {Ann Arbor, Michigan},
ABSTRACT =      {Computer Games are interesting test beds for research in Artificial Intelligence and Machine Learning. Games usually have continuous state spaces, large action spaces and  are characterized by complex relationships between components. Without applying abstraction and generalizations, learning in computer games domain becomes infeasible. Through this work, we investigate some designs that facilitate tractable reinforcement learning in symbolic agents developed using Soar architecture operating in a complex domain, Infinite Mario. Object oriented representations of the environment greatly simplify otherwise complex state spaces. We also demonstrate that imposing hierarchy in problem structure greatly reduces the complexity of the tasks and aids in learning generalized policies that can be transferred across similar tasks.},
year = {2009},
url = {http://sitemaker.umich.edu/SoarWeb/Publications/da.data/000000000000000000000000000000000000000003005536/Downloadpaper/filename},
type_publi = {techreport},
pdf = {http://sitemaker.umich.edu/SoarWeb/Publications/da.data/000000000000000000000000000000000000000003005536/Downloadpaper/filename},
type_publi = {techreport},
}
</div>
#+end_html
 
