#+TITLE:  
#+AUTHOR:    
#+EMAIL:     
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+latex_header: \usepackage{fontspec} 
#+latex_header: \usepackage{bbding}					%for loading fonts
#+latex_header: \usepackage{xunicode,xltxtra,url,parskip} 	%other packages for formatting
#+latex_header: \RequirePackage{color,graphicx}
#+latex_header: \usepackage[usenames,dvipsnames]{xcolor}
#+latex_header: \usepackage{fullpage}
#+latex_header: \usepackage{titlesec}					%custom \section
#+latex_header: \usepackage{hyperref}
#+latex_header: \definecolor{linkcolour}{rgb}{0.6,0,0}
#+latex_header: \hypersetup{colorlinks,breaklinks,urlcolor=linkcolour, linkcolor=linkcolour}
#+latex_header: \defaultfontfeatures{Mapping=tex-text}
#+latex_header: \setmainfont[SmallCapsFont = Linux Libertine Capitals O]{Linux Libertine O}
#+latex_header: \usepackage{natbib}
#+latex_header: \usepackage{bibentry}
#+latex_header: \newcommand{\bibverse}[1]{\begin{verse} \bibentry{#1}. \end{verse}}
#+latex_header: \nobibliography*

#+begin_latex
\titleformat{\section}{\Large\scshape\raggedright}{}{0em}{}[\titlerule]
\titlespacing{\section}{0pt}{3pt}{3pt}
\hyphenation{im-pre-se}
\pagestyle{empty} % non-numbered pages

\font\fb=''[cmr10]'' %for use with \LaTeX command

\par{
		{\Huge  Shiwali Mohan\\
\normalsize{
 \hfill{\Envelope} 	2260 Hayward Street \#3844, Computer Science and Engineering Building, Ann Arbor MI 48109 \\
 {\Phone} 734-757-0354    {\Envelope} \href{mailto:shiwali@umich.edu}{shiwali@umich.edu}  {\HandRight} \href{www.shiwali.me}{www.shiwali.me}
	}
}\bigskip\par}
#+end_latex

* Education
Doctor of Philosophy in /[[http://www.cse.umich.edu/][Computer Science and Engineering]]/  \hfill /August
2009 - Present/ \\
*University of Michigan*, Ann Arbor \\
Thesis: Learning to ground verbs in actions through situated
interactive instruction for cognitive agents embodied in physical
worlds. \\
Areas of interest: linguistic human-robot interaction, learning from
human-robot interaction, embodied language processing, cognitive
architectures and agents

Master of Science and Engineering in /[[http://www.cse.umich.edu/][Computer Science and Engineering]]/ \hfill
/August 2008 - December 2009/\\
*University of Michigan*, Ann Arbor\\
Relevant coursework: Introductory/Advanced Artificial Intelligence,
Machine Learning, Natural Language Processing, Models of Cognition,
Cognitive Functioning, Algorithms, Parallel Computing, Psychology of
Language

Bachelor of Engineering in /[[http://www.nsitonline.in/departments/ice.html][Instrumentation and Control
Engineering]]/ \hfill /August 2003 - May 2007/\\
Netaji Subhas Institute of Technology, *Delhi University*, New Delhi,
India\\
Thesis: Extraction based summarization of documents
* Research Experience
 Graduate Student Research Assistant to Professor [[http://ai.eecs.umich.edu/people/laird/][John E. Laird]] \hfill
 /August 2010 - Present/\\
*[[http://www.umich.edu][University of Michigan]]*, Ann Arbor\\
/Learning with human-agent interaction/  \\
Studying interaction and learning paradigms for collaborative
intelligent agents embedded in physical worlds that can acquire novel
tasks knowledge from linguistic human agent interaction. 

/Grounded language for physical agents/\\
Investigating comprehension and acquisition of grounded
representations of language for effective linguistic human-agent
interaction for robotic agents. 

 Graduate Student Research Assistant to Professor [[http://ai.eecs.umich.edu/people/laird/][John E. Laird]] \hfill
 /May 2009 - August 2010/\\
*[[http://www.umich.edu][University of Michigan]]*, Ann Arbor\\
/Reinforcement learning in Soar cognitive architecture/\\
 Designed, implemented, and analyzed reinforcement learning agents for
 Infinite Mario. Implemented modular reinforcement learning for Soar cognitive
 architecture that allows the agent to learn multiple MDPs. 

Research Assistant to Professor [[http://maths.iitd.ac.in/people/faculty/niladri_chatterjee.php][Niladri Chatterjee]] \hfill /May
2007 - May 2007/ \\
*[[http://www.iitd.ac.in][Indian Institute of Technology]]*, New Delhi, India\\
/Sense disambiguation, Word-Space models for language/\\
Designed, implemented and analyzed algorithm for sense disambiguation
of homonyms using K-Means clustering and Random Indexing.

Undergraduate Thesis with Professor [[http://maths.iitd.ac.in/people/faculty/niladri_chatterjee.php][Niladri Chatterjee]] \hfill /December
2006 - May 2007/ \\
*[[http://www.iitd.ac.in][Indian Institute of Technology]]*, New Delhi, India\\
/Single document summarization, Word-Space models for language/\\
Designed, implemented and analyzed algorithm for single-document
summarization using PageRank and Random Indexing.

* Publications
** _Journal Articles_
\bibentry{Mohan2012f}

** _Conference/Symposium Proceedings_
\bibentry{Laird2013}

\bibentry{Mohan2013a}

\bibentry{Joshi2012b}

\bibentry{Mohan2012g}
 
\bibentry{Joshi2012a}

\bibentry{Mohan2011a}

\bibentry{Mohan2011b}

\bibentry{Mohan2008}

\bibentry{Mohan2007}
** _Workshop Proceedings_
\bibentry{Mohan2012d}

\bibentry{Mohan2012c}
** _Short Papers and Extended Abstracts_
\bibentry{Joshi2012}

\bibentry{Mohan2012a}

\bibentry{Mohan2012b}

\bibentry{Mohan2010}
* Teaching Experience
Graduate Student Instructor \hfill /January 2012 - April 2012/\\
EECS 492: Introduction to Artificial Intelligence \\
*University of Michigan*, Ann Arbor

Student\hfill /September 2011 - December 2011/\\
CHE 580: Teaching Engineering \\
*University of Michigan*
* Advising Experience
Undergraduate Student Advising \hfill /September 2012 - Present/\\
Anant Mittal, Anmol Gupta\\
Undergraduate thesis project: \emph{Designing Soar agents for planet wars}\\
*Bharati Vidyapeeth College of Engineering*, New Delhi, India\\

Undergraduate Student Advising \hfill /September 2011 - May 2012/\\
Mandar Joshi, Rakesh Khobragade, Saurabh Sarda\\
Undergraduate thesis project: \emph{Reinforcement learning agents for Infinite Mario}\\
*Visvesvaraya National Institute of Techonology*, Nagpur, India\\
* Service
#+ATTR_LaTeX: align=lp{18cm}
| 2013 | /Co-Chair/, Special Interest Group - Faculty, University of Michigan                                                                   |
| 2012 | /Co-Chair/, Special Interest Group - Faculty, University of Michigan                                                                   |
| 2011 | /Vice-President/, CSE Graduate Organization, University of Michigan                                                                    |
|      | /Social Chair/, Indian Students Association, University of Michigan                                                                    |
| 2010 | /DCO Representative/, CSE Graduate Organization, University of Michigan                                                                |
|      | /Social Chair/, Indian Students Association, University of Michigan                                                                    |
| 2007 | /Creative Head/, The Choreography Team, Netaji Subhas Institute of Technology, Delhi                                                   |
| 2006 | /Volunteer/, The Neighborhood Project, Netaji Subhas Institute of Technology, Delhi                                                    |
* Industry Experience
Software Engineer with Strategic Data Services \hfill /July 2007 -
July 2008/\\
*[[http://bangalore.yahoo.com][Yahoo! Research and Development]]*, India\\
Implemented feed aggregation (to generate analytic numbers
such as page views and click-through rate) for many Yahoo!
websites on a custom distributed computing platform. Implemented
better scheduling of I/O and CPU bound processes leading to
performance improvement of Media Analytics processes.

Software Intern \hfill /May 2006 -
July 2006/\\          
*[[http://www.bel-india.com/][Bharat Electronics Limited]]*, India

Software Intern \hfill /May 2005 -
July 2005/\\
*Central Research Laboratory*, *[[http://www.bel-india.com/][Bharat Electronics Limited]]*, India
* Technical Skills
Operating Systems: Linux(Ubuntu/Red Hat), Windows(XP/Vista/7) \\
Programming Languages: \textsc{C/C++}, \textsc{Java}, Perl, Soar,
Python, JavaScript  \\
Document Markup Language: Latex
* References
available on request.

#+begin_latex
\nobibliography{../my_library}
\bibliographystyle{plain}
#+end_latex


